default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

test:
  <<: *default
  database: rails_nested_attributes_test

production:
  primary: &primary_production
    <<: *default
    database: rails_nested_attributes_production
    username: rails_nested_attributes
    password: <%= ENV["RAILS_NESTED_ATTRIBUTES_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_nested_attributes_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_nested_attributes_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_nested_attributes_production_cable
    migrations_paths: db/cable_migrate
